services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "3600"
      - "--rolling-restart"
      - "--cleanup"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - viralkan-web
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:8444"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:8081"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "8081:8081"
      - "8444:8444"
    volumes:
      - viralkan-letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - viralkan-web

  api:
    image: ghcr.io/${GITHUB_REPOSITORY}/viralkan-api:${IMAGE_TAG:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.viralkan-api-subdomain.rule=Host(`viral-api.faldi.xyz`)"
      - "traefik.http.routers.viralkan-api-subdomain.entrypoints=websecure"
      - "traefik.http.routers.viralkan-api-subdomain.tls.certresolver=myresolver"
      - "traefik.http.routers.viralkan-api-subdomain.service=viralkan-api-service"
      - "traefik.http.services.viralkan-api-service.loadbalancer.server.port=3000"
      - "traefik.docker.network=viralkan-web"
      - "com.centurylinklabs.watchtower.enable=true"
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/viralkan
      - JWT_SECRET=${JWT_SECRET}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL}
      - AI_MODEL_FREE=${AI_MODEL_FREE}
      - AI_MODEL_PAID=${AI_MODEL_PAID}
      - AI_MAX_TOKENS=${AI_MAX_TOKENS}
      - AI_TEMPERATURE=${AI_TEMPERATURE}
      - PORT=3000
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
    restart: always
    networks:
      - viralkan-web
      - viralkan-app_default
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    image: ghcr.io/${GITHUB_REPOSITORY}/viralkan-web:${IMAGE_TAG:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.viralkan-web-router.rule=Host(`viral.faldi.xyz`)"
      - "traefik.http.routers.viralkan-web-router.entrypoints=websecure"
      - "traefik.http.routers.viralkan-web-router.tls.certresolver=myresolver"
      - "traefik.http.services.viralkan-web-service.loadbalancer.server.port=3000"
      - "traefik.docker.network=viralkan-web"
      - "com.centurylinklabs.watchtower.enable=true"
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
    depends_on:
      api:
        condition: service_healthy
    restart: always
    networks:
      - viralkan-web
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  viralkan-letsencrypt:

networks:
  viralkan-web:
    driver: bridge
  viralkan-app_default:
    external: true
