services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=viralkan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - viralkan-private # Only private network - NOT connected to edge
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    image: ghcr.io/${GITHUB_REPOSITORY}/viralkan-api:${IMAGE_TAG:-latest}
    labels:
      caddy: viral-api.faldi.xyz
      caddy.reverse_proxy: "{{upstreams 3000}}"
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      - NODE_ENV=production
      - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/viralkan
      - JWT_SECRET=${JWT_SECRET}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL}
      - AI_MODEL_FREE=${AI_MODEL_FREE}
      - AI_MODEL_PAID=${AI_MODEL_PAID}
      - AI_MAX_TOKENS=${AI_MAX_TOKENS}
      - AI_TEMPERATURE=${AI_TEMPERATURE}
      - PORT=3000
    restart: always
    networks:
      - edge
      - viralkan-private
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - edge
    environment:
      - CADDY_INGRESS_NETWORKS=edge
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  web:
    image: ghcr.io/${GITHUB_REPOSITORY}/viralkan-web:${IMAGE_TAG:-latest}
    labels:
      caddy: viral.faldi.xyz
      caddy.reverse_proxy: "{{upstreams 3000}}"
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    restart: always
    networks:
      - edge
      - viralkan-private

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  edge:
    external: true
  viralkan-private:
    driver: bridge
