// DEV ONLY — static list of real Bekasi street names for seed data

export const bekasiStreets = [
  "Jl. Ir. H. Juanda",
  "Jl. Ahmad Yani",
  "Jl. Cut Meutia",
  "Jl. Siliwangi",
  "Jl. Hasanuddin",
  "Jl. Sudirman",
  "Jl. Diponegoro",
  "Jl. Kartini",
  "Jl. Wahidin",
  "Jl. Perintis Kemerdekaan",
  "Jl. Pramuka",
  "Jl. Sultan Agung",
  "Jl. K.H. Noer Ali",
  "Jl. Raya Bekasi",
  "Jl. Cikunir",
  "Jl. Pengasinan",
  "Jl. Narogong",
  "Jl. Kalimalang",
  "Jl. Joyomartono",
  "Jl. Kemakmuran",
  "Jl. Baru",
  "Jl. Lingkar Utara",
  "Jl. Flamboyan",
  "Jl. Anggrek",
  "Jl. Melati",
  "Jl. Mawar",
  "Jl. Kenanga",
  "Jl. Veteran",
  "Jl. Merdeka",
  "Jl. Pahlawan",
  "Jl. Seroja",
  "Jl. Cempaka",
  "Jl. Bougenville",
  "Jl. Teratai",
  "Jl. Dahlia",
  "Jl. Tulip",
  "Jl. Bangau",
  "Jl. Elang",
  "Jl. Garuda",
  "Jl. Nusantara",
] as const;
